### ISSUE TITLE
Доработки

### ISSUE THREAD

**Issue by sov-87** [egsam98/ruby_currency#1]
- Надо вынести из контроллера всю логику, оставить там вызов одного сервиса, передавая ему код валюты
 - в тестах надо иметь хотя бы один успешный случай. в нашем случае - это не просто 200 код ответа, а еще и какое-то значение, причем в каком-то формате
 - https://github.com/egsam98/ruby_currency/blob/master/app/helpers/json_helper.rb, string_helpler.rb нигде не используются?
 - цепочку формировать не хардкодом, а на основе массива, который  будет задаваться  в конфиге

**Comment by egsam98** [comment]
2. Будет ли адекватен тест проверки, что ответ контролера соответствует результату работы сервиса? (в данном случае chain of responsibility)
3. Json Helper используется https://github.com/egsam98/ruby_currency/blob/master/test/controllers/api/currencies_controller_test.rb, а String Helper в https://github.com/egsam98/ruby_currency/blob/master/app/controllers/application_controller.rb
3. Под конфигом подразумевается ruby файл в директории config?
